# Generated by Django 5.1.3 on 2024-12-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('nikename', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
